from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f"missing anchor: {label}")
    return text.replace(old, new, 1)

h = Path('NotchSixty/Audio/Realtime/N60Dynamics.h')
s = h.read_text()
s = replace_once(s, '''typedef struct {\n    bool enabled;\n    float strength;\n    N60BiquadCoefficients lowShelf;\n    N60BiquadCoefficients highShelf;\n} N60LoudnessContourSnapshot;\n''', '''typedef struct {\n    bool enabled;\n    bool dialogueGateEnabled;\n    float targetLUFS;\n    float maxCorrectionDB;\n    float attackCoefficient;\n    float releaseCoefficient;\n    float measurementCoefficient;\n    N60BiquadCoefficients kWeightHighPass;\n    N60BiquadCoefficients kWeightShelf;\n} N60LoudnessMatchSnapshot;\n\ntypedef struct {\n    bool enabled;\n    float strength;\n    float fullContourMasterGainLinear;\n    float flatContourMasterGainLinear;\n    N60BiquadCoefficients lowShelf;\n    N60BiquadCoefficients highShelf;\n} N60LoudnessContourSnapshot;\n''', 'loudness structs')
s = replace_once(s, '''    N60DCOffsetFilterSnapshot dcOffsetFilter;\n    N60InfrasonicFilterSnapshot infrasonicFilter;\n    N60LoudnessContourSnapshot loudnessContour;\n''', '''    N60DCOffsetFilterSnapshot dcOffsetFilter;\n    N60InfrasonicFilterSnapshot infrasonicFilter;\n    N60LoudnessMatchSnapshot loudnessMatch;\n    N60LoudnessContourSnapshot loudnessContour;\n''', 'snapshot field')
s = replace_once(s, '''    N60BiquadState loudnessLowShelfLeft;\n''', '''    N60BiquadState loudnessKWeightHighPassLeft;\n    N60BiquadState loudnessKWeightHighPassRight;\n    N60BiquadState loudnessKWeightShelfLeft;\n    N60BiquadState loudnessKWeightShelfRight;\n    float loudnessMeanSquare;\n    float loudnessMatchGainDB;\n    bool loudnessMeasurementPrimed;\n    N60BiquadState loudnessLowShelfLeft;\n''', 'runtime loudness')
s = replace_once(s, '''    float compressorGainReductionDB;\n''', '''    float loudnessShortTermLUFS;\n    float loudnessMatchGainDB;\n    float loudnessContourScale;\n    float compressorGainReductionDB;\n''', 'telemetry loudness')
s = replace_once(s, '''bool N60DynamicsSnapshotSetLoudnessContour(\n''', '''bool N60DynamicsSnapshotSetLoudnessMatch(\n    N60DynamicsSnapshot * _Nonnull snapshot,\n    double sampleRate,\n    bool enabled,\n    bool dialogueGateEnabled,\n    float targetLUFS,\n    float maxCorrectionDB,\n    float attackSeconds,\n    float releaseSeconds\n);\n\nbool N60DynamicsSnapshotSetLoudnessContour(\n''', 'loudness setter declaration')
s = replace_once(s, '''void N60DynamicsProcessCoreStereoFrame(\n    N60DynamicsRuntime * _Nonnull runtime,\n    N60DynamicsSnapshot snapshot,\n    float * _Nonnull left,\n    float * _Nonnull right\n);\n''', '''void N60DynamicsProcessCoreStereoFrame(\n    N60DynamicsRuntime * _Nonnull runtime,\n    N60DynamicsSnapshot snapshot,\n    float * _Nonnull left,\n    float * _Nonnull right\n);\nvoid N60DynamicsProcessCoreStereoFrameWithMasterGain(\n    N60DynamicsRuntime * _Nonnull runtime,\n    N60DynamicsSnapshot snapshot,\n    float masterGainLinear,\n    float * _Nonnull left,\n    float * _Nonnull right\n);\n''', 'core master function')
h.write_text(s)

c = Path('NotchSixty/Audio/Realtime/N60Dynamics.c')
s = c.read_text()
s = replace_once(s, '#define N60_LOUDNESS_MAX_TREBLE_DB 3.0\n', '''#define N60_LOUDNESS_MAX_TREBLE_DB 3.0\n#define N60_LOUDNESS_K_HIGH_PASS_HZ 38.13547087602444\n#define N60_LOUDNESS_K_HIGH_PASS_Q 0.5003270373238773\n#define N60_LOUDNESS_K_SHELF_HZ 1681.974450955533\n#define N60_LOUDNESS_K_SHELF_Q 0.7071752369554196\n#define N60_LOUDNESS_K_SHELF_DB 3.999843853973347\n#define N60_LOUDNESS_MEASUREMENT_SECONDS 3.0\n#define N60_LOUDNESS_GATE_LUFS -60.0f\n#define N60_LOUDNESS_FULL_CONTOUR_DB -30.0f\n#define N60_LOUDNESS_FLAT_CONTOUR_DB -6.0f\n''', 'constants')
s = replace_once(s, '''    snapshot.loudnessContour.enabled = false;\n    snapshot.loudnessContour.strength = 1.0f;\n''', '''    snapshot.loudnessMatch.enabled = false;\n    snapshot.loudnessMatch.dialogueGateEnabled = false;\n    snapshot.loudnessMatch.targetLUFS = -16.0f;\n    snapshot.loudnessMatch.maxCorrectionDB = 12.0f;\n    snapshot.loudnessMatch.attackCoefficient = coefficient_for_time_ms(sampleRate, 1000.0f);\n    snapshot.loudnessMatch.releaseCoefficient = coefficient_for_time_ms(sampleRate, 3000.0f);\n    snapshot.loudnessMatch.measurementCoefficient = (float)exp(-1.0 / (sampleRate * N60_LOUDNESS_MEASUREMENT_SECONDS));\n    snapshot.loudnessMatch.kWeightHighPass = N60BiquadCoefficientsMakeIdentity();\n    snapshot.loudnessMatch.kWeightShelf = N60BiquadCoefficientsMakeIdentity();\n\n    snapshot.loudnessContour.enabled = false;\n    snapshot.loudnessContour.strength = 1.0f;\n    snapshot.loudnessContour.fullContourMasterGainLinear = db_to_linear(N60_LOUDNESS_FULL_CONTOUR_DB);\n    snapshot.loudnessContour.flatContourMasterGainLinear = db_to_linear(N60_LOUDNESS_FLAT_CONTOUR_DB);\n''', 'bypassed loudness defaults')
anchor = '''bool N60DynamicsSnapshotSetLoudnessContour(\n    N60DynamicsSnapshot *snapshot,\n'''
insert = '''bool N60DynamicsSnapshotSetLoudnessMatch(\n    N60DynamicsSnapshot *snapshot,\n    double sampleRate,\n    bool enabled,\n    bool dialogueGateEnabled,\n    float targetLUFS,\n    float maxCorrectionDB,\n    float attackSeconds,\n    float releaseSeconds\n) {\n    if (snapshot == NULL || !isfinite(sampleRate) || sampleRate <= 0.0\n        || !isfinite(targetLUFS) || targetLUFS < -24.0f || targetLUFS > -10.0f\n        || !isfinite(maxCorrectionDB) || maxCorrectionDB < 3.0f || maxCorrectionDB > 20.0f\n        || !isfinite(attackSeconds) || attackSeconds < 0.3f || attackSeconds > 5.0f\n        || !isfinite(releaseSeconds) || releaseSeconds < 1.0f || releaseSeconds > 10.0f\n        || N60_LOUDNESS_K_SHELF_HZ >= sampleRate * 0.45) return false;\n\n    N60LoudnessMatchSnapshot configured = {0};\n    configured.enabled = enabled;\n    configured.dialogueGateEnabled = dialogueGateEnabled;\n    configured.targetLUFS = targetLUFS;\n    configured.maxCorrectionDB = maxCorrectionDB;\n    configured.attackCoefficient = coefficient_for_time_ms(sampleRate, attackSeconds * 1000.0f);\n    configured.releaseCoefficient = coefficient_for_time_ms(sampleRate, releaseSeconds * 1000.0f);\n    configured.measurementCoefficient = (float)exp(-1.0 / (sampleRate * N60_LOUDNESS_MEASUREMENT_SECONDS));\n    if (!valid_coefficient(configured.attackCoefficient)\n        || !valid_coefficient(configured.releaseCoefficient)\n        || !valid_coefficient(configured.measurementCoefficient)\n        || !N60BiquadDesign(N60BiquadFilterTypeHighPass, sampleRate, N60_LOUDNESS_K_HIGH_PASS_HZ, 0.0, N60_LOUDNESS_K_HIGH_PASS_Q, &configured.kWeightHighPass)\n        || !N60BiquadDesign(N60BiquadFilterTypeHighShelf, sampleRate, N60_LOUDNESS_K_SHELF_HZ, N60_LOUDNESS_K_SHELF_DB, N60_LOUDNESS_K_SHELF_Q, &configured.kWeightShelf)) return false;\n    snapshot->loudnessMatch = configured;\n    return true;\n}\n\n'''
s = replace_once(s, anchor, insert + anchor, 'loudness match setter')
s = replace_once(s, '''    configured.enabled = enabled;\n    configured.strength = strength;\n''', '''    configured.enabled = enabled;\n    configured.strength = strength;\n    configured.fullContourMasterGainLinear = db_to_linear(N60_LOUDNESS_FULL_CONTOUR_DB);\n    configured.flatContourMasterGainLinear = db_to_linear(N60_LOUDNESS_FLAT_CONTOUR_DB);\n''', 'contour thresholds')
s = replace_once(s, '''    if (!isfinite(snapshot.loudnessContour.strength) || snapshot.loudnessContour.strength < 0.0f || snapshot.loudnessContour.strength > 1.0f\n''', '''    if (!isfinite(snapshot.loudnessMatch.targetLUFS) || snapshot.loudnessMatch.targetLUFS < -24.0f || snapshot.loudnessMatch.targetLUFS > -10.0f\n        || !isfinite(snapshot.loudnessMatch.maxCorrectionDB) || snapshot.loudnessMatch.maxCorrectionDB < 3.0f || snapshot.loudnessMatch.maxCorrectionDB > 20.0f\n        || !valid_coefficient(snapshot.loudnessMatch.attackCoefficient)\n        || !valid_coefficient(snapshot.loudnessMatch.releaseCoefficient)\n        || !valid_coefficient(snapshot.loudnessMatch.measurementCoefficient)\n        || !N60BiquadCoefficientsAreFinite(snapshot.loudnessMatch.kWeightHighPass)\n        || !N60BiquadCoefficientsAreFinite(snapshot.loudnessMatch.kWeightShelf)) return false;\n    if (!isfinite(snapshot.loudnessContour.strength) || snapshot.loudnessContour.strength < 0.0f || snapshot.loudnessContour.strength > 1.0f\n        || !isfinite(snapshot.loudnessContour.fullContourMasterGainLinear) || snapshot.loudnessContour.fullContourMasterGainLinear <= 0.0f\n        || !isfinite(snapshot.loudnessContour.flatContourMasterGainLinear) || snapshot.loudnessContour.flatContourMasterGainLinear <= snapshot.loudnessContour.fullContourMasterGainLinear\n''', 'validation')

old = '''static void process_loudness_contour(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float *left,\n    float *right\n) {\n'''
new = '''static void process_loudness_match(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float *left,\n    float *right\n) {\n    float weightedLeft = N60BiquadProcessSample(snapshot.loudnessMatch.kWeightHighPass, &runtime->loudnessKWeightHighPassLeft, *left);\n    weightedLeft = N60BiquadProcessSample(snapshot.loudnessMatch.kWeightShelf, &runtime->loudnessKWeightShelfLeft, weightedLeft);\n    float weightedRight = N60BiquadProcessSample(snapshot.loudnessMatch.kWeightHighPass, &runtime->loudnessKWeightHighPassRight, *right);\n    weightedRight = N60BiquadProcessSample(snapshot.loudnessMatch.kWeightShelf, &runtime->loudnessKWeightShelfRight, weightedRight);\n    float instantMeanSquare = 0.5f * (weightedLeft * weightedLeft + weightedRight * weightedRight);\n    if (!runtime->loudnessMeasurementPrimed && instantMeanSquare > N60_DYNAMICS_EPSILON) {\n        runtime->loudnessMeanSquare = instantMeanSquare;\n        runtime->loudnessMeasurementPrimed = true;\n    } else {\n        runtime->loudnessMeanSquare = smooth_toward(runtime->loudnessMeanSquare, instantMeanSquare, snapshot.loudnessMatch.measurementCoefficient);\n    }\n    float measuredLUFS = -0.691f + 10.0f * log10f(fmaxf(runtime->loudnessMeanSquare, N60_DYNAMICS_EPSILON));\n    float targetGainDB = 0.0f;\n    if (snapshot.loudnessMatch.enabled && !(snapshot.loudnessMatch.dialogueGateEnabled && measuredLUFS < N60_LOUDNESS_GATE_LUFS)) {\n        targetGainDB = clampf(snapshot.loudnessMatch.targetLUFS - measuredLUFS, -snapshot.loudnessMatch.maxCorrectionDB, snapshot.loudnessMatch.maxCorrectionDB);\n    }\n    float coefficient = targetGainDB < runtime->loudnessMatchGainDB\n        ? snapshot.loudnessMatch.attackCoefficient\n        : snapshot.loudnessMatch.releaseCoefficient;\n    if (!snapshot.loudnessMatch.enabled) coefficient = snapshot.bypassTransitionCoefficient;\n    runtime->loudnessMatchGainDB = smooth_toward(runtime->loudnessMatchGainDB, targetGainDB, coefficient);\n    float gain = db_to_linear(runtime->loudnessMatchGainDB);\n    *left *= gain;\n    *right *= gain;\n}\n\nstatic void process_loudness_contour(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float masterGainLinear,\n    float *left,\n    float *right\n) {\n'''
s = replace_once(s, old, new, 'process loudness functions')
s = replace_once(s, '''    float target = snapshot.loudnessContour.enabled ? 1.0f : 0.0f;\n    runtime->loudnessMix = smooth_toward(runtime->loudnessMix, target, snapshot.bypassTransitionCoefficient);\n''', '''    float volumeScale = 0.0f;\n    if (masterGainLinear <= snapshot.loudnessContour.fullContourMasterGainLinear) {\n        volumeScale = 1.0f;\n    } else if (masterGainLinear < snapshot.loudnessContour.flatContourMasterGainLinear) {\n        float masterDB = linear_to_db(masterGainLinear);\n        volumeScale = (N60_LOUDNESS_FLAT_CONTOUR_DB - masterDB) / (N60_LOUDNESS_FLAT_CONTOUR_DB - N60_LOUDNESS_FULL_CONTOUR_DB);\n        volumeScale = clampf(volumeScale, 0.0f, 1.0f);\n    }\n    float target = snapshot.loudnessContour.enabled ? volumeScale : 0.0f;\n    runtime->loudnessMix = smooth_toward(runtime->loudnessMix, target, snapshot.bypassTransitionCoefficient);\n''', 'volume-aware contour mix')

old_core = '''void N60DynamicsProcessCoreStereoFrame(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float *left,\n    float *right\n) {\n    if (runtime == NULL || left == NULL || right == NULL) return;\n\n    process_stereo_mode(runtime, snapshot, left, right);\n    process_stereo_widener(runtime, snapshot, left, right);\n    process_loudness_contour(runtime, snapshot, left, right);\n'''
new_core = '''void N60DynamicsProcessCoreStereoFrameWithMasterGain(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float masterGainLinear,\n    float *left,\n    float *right\n) {\n    if (runtime == NULL || left == NULL || right == NULL) return;\n    if (!isfinite(masterGainLinear) || masterGainLinear < 0.0f) masterGainLinear = 1.0f;\n\n    process_stereo_mode(runtime, snapshot, left, right);\n    process_stereo_widener(runtime, snapshot, left, right);\n    process_loudness_match(runtime, snapshot, left, right);\n    process_loudness_contour(runtime, snapshot, masterGainLinear, left, right);\n'''
s = replace_once(s, old_core, new_core, 'core body')
# Insert compatibility wrapper before pause gate.
anchor = 'void N60DynamicsProcessPauseGateStereoFrame(\n'
wrapper = '''void N60DynamicsProcessCoreStereoFrame(\n    N60DynamicsRuntime *runtime,\n    N60DynamicsSnapshot snapshot,\n    float *left,\n    float *right\n) {\n    N60DynamicsProcessCoreStereoFrameWithMasterGain(runtime, snapshot, 1.0f, left, right);\n}\n\n'''
s = replace_once(s, anchor, wrapper + anchor, 'core wrapper')
s = replace_once(s, '''    telemetry.deEsserGainReductionDB = fmaxf(0.0f, -runtime->deEsserGainDB);\n''', '''    telemetry.loudnessShortTermLUFS = -0.691f + 10.0f * log10f(fmaxf(runtime->loudnessMeanSquare, N60_DYNAMICS_EPSILON));\n    telemetry.loudnessMatchGainDB = runtime->loudnessMatchGainDB;\n    telemetry.loudnessContourScale = runtime->loudnessMix;\n    telemetry.deEsserGainReductionDB = fmaxf(0.0f, -runtime->deEsserGainDB);\n''', 'telemetry values')
c.write_text(s)

rk = Path('NotchSixty/Audio/Realtime/N60RenderKernel.c')
s = rk.read_text()
s = replace_once(s, 'N60DynamicsProcessCoreStereoFrame(&kernel->dynamicsRuntime, context->snapshot.dynamics, &left, &right);', 'N60DynamicsProcessCoreStereoFrameWithMasterGain(&kernel->dynamicsRuntime, context->snapshot.dynamics, context->snapshot.masterGainLinear, &left, &right);', 'render kernel master gain')
rk.write_text(s)

swift = Path('NotchSixty/Audio/DynamicsConfiguration.swift')
s = swift.read_text()
s = replace_once(s, '    case invalidLoudnessContour\n', '    case invalidLoudnessMatch\n    case invalidLoudnessContour\n', 'swift error case')
s = replace_once(s, '        case .invalidLoudnessContour:\n', '        case .invalidLoudnessMatch:\n            return "LUFS Loudness Match parameters are outside the supported production range."\n        case .invalidLoudnessContour:\n', 'swift error text')
anchor = 'struct LoudnessContourConfiguration: Equatable, Sendable {\n'
block = '''struct LoudnessMatchConfiguration: Equatable, Sendable {\n    static let targetRange = -24.0 ... -10.0\n    static let maxCorrectionRange = 3.0...20.0\n    static let attackRange = 0.3...5.0\n    static let releaseRange = 1.0...10.0\n\n    var enabled = false\n    var dialogueGateEnabled = false\n    var targetLUFS = -16.0\n    var maxCorrectionDB = 12.0\n    var attackSeconds = 1.0\n    var releaseSeconds = 3.0\n\n    func validate() throws {\n        guard targetLUFS.isFinite, Self.targetRange.contains(targetLUFS),\n              maxCorrectionDB.isFinite, Self.maxCorrectionRange.contains(maxCorrectionDB),\n              attackSeconds.isFinite, Self.attackRange.contains(attackSeconds),\n              releaseSeconds.isFinite, Self.releaseRange.contains(releaseSeconds) else {\n            throw DynamicsConfigurationError.invalidLoudnessMatch\n        }\n    }\n}\n\n'''
s = replace_once(s, anchor, block + anchor, 'swift loudness config')
s = replace_once(s, '    var loudnessContour = LoudnessContourConfiguration()\n', '    var loudnessMatch = LoudnessMatchConfiguration()\n    var loudnessContour = LoudnessContourConfiguration()\n', 'swift property')
s = replace_once(s, '        try loudnessContour.validate()\n', '        try loudnessMatch.validate()\n        try loudnessContour.validate()\n', 'swift validation')
s = replace_once(s, '        guard N60DynamicsSnapshotSetLoudnessContour(&snapshot, sampleRate, loudnessContour.enabled, Float(loudnessContour.strength)) else { throw DynamicsConfigurationError.invalidLoudnessContour }\n', '''        guard N60DynamicsSnapshotSetLoudnessMatch(\n            &snapshot,\n            sampleRate,\n            loudnessMatch.enabled,\n            loudnessMatch.dialogueGateEnabled,\n            Float(loudnessMatch.targetLUFS),\n            Float(loudnessMatch.maxCorrectionDB),\n            Float(loudnessMatch.attackSeconds),\n            Float(loudnessMatch.releaseSeconds)\n        ) else { throw DynamicsConfigurationError.invalidLoudnessMatch }\n        guard N60DynamicsSnapshotSetLoudnessContour(&snapshot, sampleRate, loudnessContour.enabled, Float(loudnessContour.strength)) else { throw DynamicsConfigurationError.invalidLoudnessContour }\n''', 'swift snapshot setter')
swift.write_text(s)

print('PR29 loudness integration applied')
