from pathlib import Path

path = Path('.github/scripts/pr41_slice_c1.py')
text = path.read_text()

old = """catalog = replace_once(\n    catalog,\n    '''            nominalSampleRate: try readNominalSampleRate(deviceID: deviceID),\\n            availableSampleRateRanges: try readAvailableSampleRateRanges(deviceID: deviceID)\\n        )\\n''',\n    '''            nominalSampleRate: try readNominalSampleRate(deviceID: deviceID),\\n            availableSampleRateRanges: try readAvailableSampleRateRanges(deviceID: deviceID),\\n            outputChannelCount: try readOutputChannelCount(deviceID: deviceID)\\n        )\\n''',\n    \"Output device channel count construction\",\n)\n"""
new = """catalog = replace_once(\n    catalog,\n    '''    static func makeOutputDevice(deviceID: AudioDeviceID) throws -> AudioOutputDevice {\\n        AudioOutputDevice(\\n            deviceID: deviceID,\\n            uid: try readString(\\n                deviceID: deviceID,\\n                selector: kAudioDevicePropertyDeviceUID,\\n                operation: .readDeviceUID\\n            ),\\n            name: try readString(\\n                deviceID: deviceID,\\n                selector: kAudioObjectPropertyName,\\n                operation: .readDeviceName\\n            ),\\n            nominalSampleRate: try readNominalSampleRate(deviceID: deviceID),\\n            availableSampleRateRanges: try readAvailableSampleRateRanges(deviceID: deviceID)\\n        )\\n    }\\n''',\n    '''    static func makeOutputDevice(deviceID: AudioDeviceID) throws -> AudioOutputDevice {\\n        AudioOutputDevice(\\n            deviceID: deviceID,\\n            uid: try readString(\\n                deviceID: deviceID,\\n                selector: kAudioDevicePropertyDeviceUID,\\n                operation: .readDeviceUID\\n            ),\\n            name: try readString(\\n                deviceID: deviceID,\\n                selector: kAudioObjectPropertyName,\\n                operation: .readDeviceName\\n            ),\\n            nominalSampleRate: try readNominalSampleRate(deviceID: deviceID),\\n            availableSampleRateRanges: try readAvailableSampleRateRanges(deviceID: deviceID),\\n            outputChannelCount: try readOutputChannelCount(deviceID: deviceID)\\n        )\\n    }\\n''',\n    \"Output device channel count construction\",\n)\n"""
if text.count(old) != 1:
    raise SystemExit(f'expected one output-device catalog helper block, found {text.count(old)}')
text = text.replace(old, new, 1)
path.write_text(text)
print('PR41 C1 catalog helper targeting fixed')
